### ISSUE TITLE
Couldn't able view Console in Web

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo#30]
After the successful installation I could able to coonect my xenservers but when I click the <Host Console> I couldn't see the console in browser.

I tried in my Chrome 38.0.2125.111 / Firefox 33.0 / IE 11

Do I need anything to install to view the console.

**Comment by xf03** [comment]
Hi Olivier,
I have similar problem,  We are using Xen Center 6.2 and trying to play with XOA3.6.
xo-server  status say its listening on port 8080 (see below log) but am getting http 404 error message when i tried to browse http://localhost:8080
Am sure am missing some thing here....please help me. 


xo-server.service - XO Server
   Loaded: loaded (/etc/systemd/system/xo-server.service; enabled)
   Active: active (running) since Mon 2015-01-05 14:32:25 GMT; 5min ago
Main PID: 2862 (node)
   CGroup: name=systemd:/system/xo-server.service
??2862 node /root/xo-server/bin/xo-server

Jan 05 14:32:25 xoa systemd[1]: xo-server.service: main process exited, code=exited, status=143/n/a
Jan 05 14:32:25 xoa systemd[1]: Unit xo-server.service entered failed state.
Jan 05 14:32:25 xoa systemd[1]: Starting XO Server...
Jan 05 14:32:25 xoa systemd[1]: Started XO Server.
Jan 05 14:32:27 xoa xo-server[2862]: Mon, 05 Jan 2015 14:32:27 GMT xo:main Starting?
Jan 05 14:32:27 xoa xo-server[2862]: Mon, 05 Jan 2015 14:32:27 GMT xo:main Configuration loaded.
Jan 05 14:32:27 xoa xo-server[2862]: Mon, 05 Jan 2015 14:32:27 GMT xo:main Web server listening on http://0.0.0.0:8080
Jan 05 14:32:27 xoa xo-server[2862]: Mon, 05 Jan 2015 14:32:27 GMT xo:main Initializing connection to Xen servers?
Jan 05 14:32:27 xoa xo-server[2862]: Mon, 05 Jan 2015 14:32:27 GMT xo:main Setting up /  /root/xo-web/dist

**Comment by julien-f** [comment]
@xf03 Your problem does not seem to be related, are you sure you are on the same machine as the one XO is running on, normally you should use the IP address of the XO appliance.

**Comment by olivierlambert** [comment]
Yep, the log showing XOA is listening correctly on 8080 from every networks.

But if you are on your own PC, you need to access XOA through `http://<IP_OF_XOA>:8080` and not localhost.

Does it work now @xf03 ?

**Comment by olivierlambert** [comment]
For people using XO with IE11, we just fixed a bug in the console. See https://github.com/vatesfr/xo-web/issues/184

**Comment by sjkeerthi** [comment]
Still could not able to view the console on my firefox 34.0 / Chrome 39

**Comment by olivierlambert** [comment]
If you have the same output you give previously, I can see `Unexpected response code: 404`. So, your XenServer having the IP `10.3.5.12` is telling you it can't find the document you requested. Can you enter `http://10.3.5.12/console?uuid=6512d636-4eee-e790-32e6-17a272cfab75&session_id=OpaqueRef:6215bd3c-daf2-ed31-f317-2a35a50782c7` in your browser and check if you have anything?

**Comment by sjkeerthi** [comment]
Msg: noVNC ready: native WebSockets, canvas rendering
app.js:1 Array[4]
util.js:218 
app.js:1 Array[4]
websock.js:227 WebSocket connection to 'ws://./' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
websock.js:275 WebSocket connection to 'ws://10.3.5.20/console?uuid=6386e595-90dd-86af-11ac-cb08e6c77469&session_id=OpaqueRef:853af9e2-5462-fde7-cc60-7734bc788421' failed: Error during WebSocket handshake: Unexpected response code: 404
util.js:218 WebSocket on-error event
util.js:218 WebSocket on-close event
util.js:220  Msg: Server disconnected (code: 1006)
app.js:1 Array[4]
util.js:218 
app.js:1 Array[3]

**Comment by olivierlambert** [comment]
`ERR_NAME_NOT_RESOLVED` tells us that you try to access to this IP from an external network. Indeed, `10.3.5.20` is a private IP. So far, you need to be in the same network to access your console. It will be fixed as it's planned in our roadmap (Console proxy)

**Comment by olivierlambert** [comment]
Closing it after releasing 3.7. Will be reopen if needed.
