### ISSUE TITLE
VM Network Questions

### ISSUE THREAD

**Issue by guzmanbraso** [vatesfr/xo#73]
Hi!

We are evaluating using Xen Orchestra to manage all our XS pools but we were unable to find in the docs any reference to virtual machines networking configuration.

We assume this is because Xen Orchestra expects the interface assigned to a VM to always have a dhcp server in the same network ?

If we need to force an IP does Xen Orchestra support it? 

Does xen Orchestra communicate with the dhcp server to make sure for instance that the IP X is associated to MAC Y in the future ?

There's any doc around where we can learn more about the network configuration of instances and how to mess with that ?

**Comment by olivierlambert** [comment]
Hi @guzmanbraso !

XenServer works on the lower level (you can set a MAC address). That's on you to configure either a DHCP, or to create a VM and then specify its IP address (or to use a PXE server for example).

What you can do currently in a near future:

* Force a virtual interface to accept only specified IPs (see https://github.com/vatesfr/xo-web/issues/240)
* Pass a static network configuration with the help of CloudInit. I think the problem is that's not really generic across all Linux distros :/
* Use XO to provision a MAC/IP in an existing DHCP server (see https://github.com/vatesfr/xo-web/issues/351)

What's the approach you would like to investigate?
